#!/bin/bash
if [ $LOGNAME != "root" ]; then
        echo "Please run this script as root! The default password is ajtemp."
        exit 1
fi

# place the root mysql password here
webroot=/var/www/html/

#######
# gather some initial information
#######

# because this is run as root we cant grab the usernaem from $USER as it would be "root"
echo
read -p "Enter your username then press [Enter]: " USERNAME
echo

echo
read -p "Enter your MySQL root password then press [Enter]: " MYSQL_ROOT_PWD
echo
echo
read -p "Enter a password you wish to use for your worpress database" WPDBPASS
echo
# create a ftp user and add to the ww-data group
echo "Setting up ftp user..."
useradd -d $webroot wpftpuser
passwd wpftpuser
usermod -a -G www-data wpftpuser

apt-get update -y
apt-get install -y php7.0 mysql-server vsftpd apache2 libapache2-mod-php7.0 php7.0-mcrypt php7.0-gd 

mysqld --initialize
mysql_secure_installation --password="$MYSQL_ROOT_PWD" -D

service apache2 restart
#create database and user with the correct privilages
mysql --user="root" --password="$MYSQL_ROOT_PWD" \
--execute="CREATE DATABASE wordpress; CREATE USER wordpressuser@localhost IDENTIFIED BY '${WPDBPASS}'; GRANT ALL PRIVILEGES ON wordpress.* TO wordpressuser@localhost; FLUSH PRIVILEGES;"
# get the wordpress files

wget http://wordpress.org/latest.tar.gz
tar xzvf latest.tar.gz

#create config file
cp wordpress/wp-config-sample.php wordpress/wp-config.php
sed -ri "s/define('DB_NAME',.*/\define('DB_NAME', 'wordpress');/g" "wordpress/wp-config.php"
sed -ri "s/define('DB_USER',.*/\define('DB_USER', 'wordpressuser');/g" "wordpress/wp-config.php"
sed -ri "s/define('DB_PASSWORD',.*/\define('DB_PASSWORD', '${WPDBPASS}');/g" "wordpress/wp-config.php"
sed -ri "s/define('DB_HOST',.*/\define('DB_HOST', 'localhost');/g" "wordpress/wp-config.php"
sed -ri "s/define('DB_CHARSET',.*/\define('DB_CHARSET', 'utf8');/g" "wordpress/wp-config.php"
sed -ri "s/define('DB_COLLATE',.*/\define('DB_COLLATE', '');/g" "wordpress/wp-config.php"


#move files to correct directory
rsync -avP ~/wordpress/ /var/www/html/

# set permissions 
mkdir -p /var/www/html/wp-content/uploads
chown -R $USERNAME:www-data /var/www/html/*
chown -R :www-data /var/www/html/wp-content/uploads
