#!/bin/bash
if [ $LOGNAME != "root" ]; then
        echo "Please run this script as root!"
        exit 1
fi

must_succeed() {
	while true
		do
        	$1
	        if [ $? == 0 ]; then
			break
		fi
		echo
        	echo "Please try again."
		echo
	done
}
# place the root mysql password here
webroot=/var/www/html/

#######
# gather some initial information
#######

# because this is run as root we cant grab the usernaem from $USER as it would be "root"
echo
read -p "Enter your username then press [Enter]: " USERNAME
echo

echo
read -p "Enter your MySQL root password then press [Enter]: " MYSQL_ROOT_PWD
echo
echo
read -p "Enter a password you wish to use for your worpress database" WPDBPASS
echo
# create a ftp user and add to the ww-data group
echo "Setting up ftp user..."
useradd -d $webroot wpftpuser
must_succeed "passwd wpftpuser"
usermod -a -G www-data wpftpuser

apt-get update -y
apt-get install -y php7.0 mysql-server vsftpd apache2 libapache2-mod-php7.0 php7.0-mcrypt php7.0-gd 

mysqld --initialize
mysql_secure_installation --password="$MYSQL_ROOT_PWD" -D

#create database and user with the correct privilages
mysql -u root -p$MYSQL_ROOT_PWD << EOF
CREATE DATABASE wordpress; 
CREATE USER wordpressuser@localhost IDENTIFIED BY '${WPDBPASS}'; 
GRANT ALL PRIVILEGES ON wordpress.* TO wordpressuser@localhost; 
FLUSH PRIVILEGES;
EOF

# get the wordpress files

wget http://wordpress.org/latest.tar.gz
tar xzvf latest.tar.gz

#create config file
cp wordpress/wp-config-sample.php wordpress/wp-config.php

mv wordpress/wp-config.php wordpress/wp-config.in

sed "
s/define('DB_NAME.*/define('DB_NAME', 'wordpress');/
s/define('DB_USER.*/define('DB_USER', 'wordpressuser');/ 
s/define('DB_PASSWORD.*/define('DB_PASSWORD', '${WPDBPASS}');/ 
s/define('DB_HOST.*/define('DB_HOST', 'localhost');/
s/define('DB_CHARSET.*/define('DB_CHARSET', 'utf8');/
s/define('DB_COLLATE',.*/define('DB_COLLATE', '');/" wordpress/wp-config.in > wordpress/wp-config.php

rm worpress/wp-config.in

#move files to correct directory
rsync -avP ~/wordpress/ /var/www/html/

# set permissions 
mkdir -p /var/www/html/wp-content/uploads
chown -R $USERNAME:www-data /var/www/html/*
chown -R :www-data /var/www/html/wp-content/uploads

service apache2 restart
unset USERNAME
unset MYSQL_ROOT_PWD
unset WPDBPASS